version: "3"
services:
  audiocraft:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: "audiocraftContainer"
    expose:
      - "7860"
    working_dir: "/root/"
    tty: true
    ports:
      - "7860:7860"
    volumes:
      - ./src:/root/src/
    # command: sh -c 'pip install --upgrade pip && pip install -r requirements.txt'
